#ifndef _TITLE_UILAYER_VIEW_H_
#define _TITLE_UILAYER_VIEW_H_
#include "GameUILayer.h"
//#include "StructProgramInResource.h"

class TitleUILayerView : public GameUILayer
{
	UI_SIMPLE_CREATE_CLASS(TitleUILayerView, UI_TITLEUILAYER);

	void InitView();

private:
	enum TAG_TITLE_UI
	{
		TAG_TITLE_UI_CHARGE = 21,
		TAG_TITLE_UI_MAKE = 23,
		TAG_TITLE_UI_BACKPACK = 24,
		TAG_TITLE_UI_FUBEN = 25,

		TAG_TITLE_UI_HEAD = 33,

		TAG_TITLE_UI_SIGN = 40,
		TAG_TITLE_UI_NOOPEN2 = 41,
		TAG_TITLE_UI_NOOPEN3 = 42,
		TAG_TITLE_UI_NOOPEN4 = 43,

		TAG_TITLE_UI_COIN = 28,
		TAG_TITLE_UI_DIAMOND = 29,
		TAG_TITLE_UI_TILI = 45,

		TAG_TITLE_UI_SYSCONFIG = 50,
	};


};


#endif // _TITLE_UILAYER_VIEW_H_